bitrix24_integration/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm_connector.urls')),
    # path('bitrix24/', include('crm_connector.urls')),
    path('education/', include('education_planner.urls')),
    path('contacts/', include('contact_management.urls')),
]

# Добавляем отдачу статических файлов в development режиме
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

contact_management/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter
from .views import OrganizationViewSet, ContactViewSet, GetAllViewSet

router = DefaultRouter()
router.register(r'organization', OrganizationViewSet, basename='organization')
router.register(r'contact', ContactViewSet, basename='contact')
router.register(r'get_all', GetAllViewSet, basename='get_all')

app_name = 'contact_management'
 
urlpatterns = [
    path('api-guide/', views.api_guide, name="api-guide"),
    path('api/', include(router.urls)),
    path('import/', views.ContactImport, name='import')
]

crm_connector/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter
from .views import ObjectHistoryView, RegionAutocomplete, ListenerProgressViewSet

app_name = 'crm_connector'

router = DefaultRouter()
router.register(r'user-progress', ListenerProgressViewSet, basename='user-progress')

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('pipelines/', views.pipelines_dashboard, name='pipelines_dashboard'),
    path('sync/', views.sync_data, name='sync_data'),
    path('sync-pipelines/', views.sync_pipelines, name='sync_pipelines'),
    path('check-pipelines/', views.check_pipelines, name='check_pipelines'),
    path('import-deals/', views.import_deals_from_excel, name='import_deals'),
    path('crm/import-atlas/', views.import_atlas_applications, name='import_atlas_applications'),
    path('atlas-dashboard/', views.atlas_dashboard, name='atlas_dashboard'),
    path('crm/atlas-dashboard/', views.atlas_dashboard, name='crm_atlas_dashboard'),
    path('history/<str:model>/<int:pk>/', ObjectHistoryView.as_view(), name='object_history'),
    path('import-not-atlas/', views.import_not_atlas, name="import_not_atlas"),
    path('attestation-progress', views.attestation_progress, name="attestation_progress"),
    path('lead-dashboard', views.lead_dashboard, name="lead-dashboard"),
    path('attestation-stats', views.attestation_stats, name="attestation-stats"),
    path('region-autocomplete/', RegionAutocomplete.as_view(), name='region-autocomplete'),
    path('contract-generation/', views.contract_generation, name="contract_generation"),
    path('api/', include(router.urls)),
    path('api-guide/', views.api_guide, name="api-guide"),
    path('download-application/<str:snils>/', views.download_generated_application, name="download_generated_application"),
    path('applications-list/', views.applications_list, name="applications_list")
]

education_planner/urls.py
from django.urls import path
from . import views

app_name = 'education_planner'
 
urlpatterns = [
    path('', views.program_list, name='program_list'),
    path('program/create/', views.create_program, name='create_program'),
    
    # Маршруты для управления договорами
    path('agreements/', views.agreements_dashboard, name='agreements_dashboard'),
    path('agreements/<int:pk>/', views.agreement_detail, name='agreement_detail'),
    path('agreements/create/', views.create_agreement, name='create_agreement'),
    path('agreements/<int:pk>/delete/', views.delete_agreement, name='delete_agreement'),
    path('agreements/<int:pk>/supplement-quotas/', views.get_supplement_quotas, name='get_supplement_quotas'),
    
    # Маршруты для управления квотами
    path('agreements/<int:agreement_id>/quotas/', views.manage_quota, name='manage_quota'),
    path('quotas/<int:quota_id>/detail/', views.quota_detail, name='quota_detail'),
    
    # Маршруты для импорта квот
    path('quotas/analyze/', views.analyze_quotas_excel, name='analyze_quotas_excel'),
    path('quotas/regions/save/', views.save_region_mappings, name='save_region_mappings'),
    path('quotas/import/', views.import_quotas_excel, name='import_quotas_excel'),
    path('quotas/import/direct/', views.import_quotas_excel_direct, name='import_quotas_excel_direct'),
    path('quotas/template/', views.download_quota_template, name='download_quota_template'),
    
    # # Маршруты для допсоглашений
    path('agreements/<int:agreement_id>/supplements/create/', views.create_supplement, name='create_supplement'),
    path('supplements/<int:pk>/', views.supplement_detail, name='supplement_detail'),
    path('supplements/<int:pk>/edit/', views.edit_supplement, name='edit_supplement'),
    
    # Маршруты для импорта допсоглашений
    path('supplements/analyze/', views.analyze_supplement_excel, name='analyze_supplement_excel'),
    path('supplements/regions/save/', views.save_supplement_region_mappings, name='save_supplement_region_mappings'),
    path('supplements/import/', views.import_supplement_excel, name='import_supplement_excel'),
    path('supplements/template/', views.download_supplement_template, name='download_supplement_template'),
    
    # Сводный дашборд квот
    path('quota-summary/', views.quota_summary_dashboard, name='quota_summary_dashboard'),
    path('manage-roiv/', views.manage_roiv, name='manage_roiv'),
    path('manage-alternative-quota/', views.manage_alternative_quota, name='manage_alternative_quota'),
    path('manage-demand/', views.manage_demand, name='manage_demand'),
    path('distribute-quota/', views.distribute_quota, name='distribute_quota'),
] 

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Bitrix Dashboard{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <!-- Custom CSS -->
    <style>
        body {
            padding-top: 20px;
            padding-bottom: 20px;
        }
        .navbar {
            margin-bottom: 20px;
        }
        .dropdown:hover .dropdown-menu{
            display: block;
        }
    </style>
    {% block extra_css %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">Bitrix Dashboard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% if user.is_superuser or user.is_staff %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle active" href="{% url 'crm_connector:api-guide' %}" aria-expanded="false" >REST API</a>
                            <ul class="dropdown-menu" style="margin-top: 0;">
                                <li><a class="dropdown-item " href="{% url 'crm_connector:api-guide' %}">Заявки</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'contact_management:api-guide' %}">Организации</a></li>
                                <li><a class="dropdown-item" href="{% url 'contact_management:api-guide' %}?contact">Контакты</a></li>
                                <li><a class="dropdown-item" href="{% url 'contact_management:api-guide' %}?get_all">Списки</a></li>
                            </ul>
                        </li>
                    {% endif %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" aria-expanded="false">Импорт</a>
                        <ul class="dropdown-menu" style="margin-top: 0;">
                            <li><a class="dropdown-item {% if not user.is_authenticated %} disabled {% endif %}" href="{% url 'crm_connector:import_atlas_applications' %}">Импорт заявок с Атласа</a></li>
                            <li><a class="dropdown-item {% if not user.is_authenticated %} disabled {% endif %}" href="{% url 'crm_connector:import_not_atlas' %}">Импорт других заявок</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item {% if not user.is_authenticated %} disabled {% endif %}" href="{% url 'contact_management:import' %}">Импорт контактов</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" aria-expanded="false">Дашборды</a>
                        <ul class="dropdown-menu" style="margin-top: 0;">
                            <li><a class="dropdown-item" href="{% url 'crm_connector:atlas_dashboard' %}">Дашборд Атлас</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item {% if not user.is_authenticated %} disabled {% endif %}" href="{% url 'crm_connector:applications_list' %}">Список заявок</a></li>
                            <li><a class="dropdown-item {% if not user.is_authenticated %} disabled {% endif %}" href="{% url 'education_planner:quota_summary_dashboard' %}">Сводный дашборд квот</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" aria-expanded="false">Аттестации</a>
                        <ul class="dropdown-menu" style="margin-top: 0;">
                            <li><a class="dropdown-item {% if not user.is_authenticated %} disabled {% endif %}" href="{% url 'crm_connector:attestation_progress' %}">Дашборд аттестаций</a></li>
                            <li><a class="dropdown-item {% if not user.is_authenticated %} disabled {% endif %}" href="{% url 'crm_connector:attestation-stats' %}">Статистика аттестаций</a></li>
                        </ul>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link {% if not user.is_authenticated %} disabled {% else %} active {% endif %}" href="{% url 'education_planner:agreements_dashboard' %}">Договоры на обучение</a>
                    </li>

                </ul>
                
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="/admin">{{ user.username  }}<i class="bi bi-person ms-1"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-danger active" href="{% url 'crm_connector:logout' %}">Выйти<i class="bi bi-box-arrow-in-right ms-1"></i></a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        {% with url=request.path %}
                        <a class="nav-link active" href="{% url 'crm_connector:login' %}?redirect={{ url }}">Войти<i class="bi bi-box-arrow-in-right ms-1"></i></a>
                        {% endwith %}
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        {% block content %}{% endblock %}
    </div>

    <!-- Bootstrap JS Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    {% block extra_js %}{% endblock %}
</body>
</html> 